### ISSUE TITLE
Product.Price localization is based on device's settings region, not AppStore region

### ISSUE THREAD

**Issue by AytoMaximo** [adaptyteam/AdaptySDK-Unity#6]
Hello! 

We have an issue with price + currency symbol localization. We want to get price, based on AppStore region. However now we get price from the iPhone's settings region. 

For example: user's AppStore region is Russia, but iPhone's region is Great Britain (English). As the result this user gets price in dollars, not RUB, but it should be the opposite. 

So, the SDK returns NOT the same price + currency, which will be showed next in the system IAP popup. 

How can we fix this? Thank you in advance.

**Comment by AytoMaximo** [comment]
Hi, @x401om! We've found out the issue is caused by no callback response after calling Adapty.GetPaywals() method. 
So, my first thought was we get the wrong currency, but in fact we get no price and currency at all: we see hardcoded UI values. 

And we face this no callback issue is two different projects. Also we've analyzed analytics events and found some dependency between drop-off and user's region. For example, everything is OK for USA, but very bad for UK and Australia.

**Comment by x401om** [comment]
@AytoMaximo I checked with my colleagues and we decided that it would be best if you emailed us at support@adapty.io or at Intercom on our website, if you have access to it. They already know about your problem and will help you solve it quickly.
